version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - mkdir -p certs
      - curl -o certs/global-bundle.pem https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
  build:
    commands:
      - mvn clean package -DskipTests
      - mkdir -p backend
      - mv target/*.jar backend/app.jar
artifacts:
  files:
    - backend/**
    - scripts/**
    - certs/**
    - docker-compose.yml