ALTER TABLE feedbacks
    ADD COLUMN IF NOT EXISTS is_visiting BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_mobile   BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS language    VARCHAR(2);
